name: selllout
description: Sell everything & anything!

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.2+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  cloud_firestore: ^3.4.9
  firebase_auth: ^3.10.0
  firebase_core: ^1.23.0
  firebase_storage: ^10.3.9

  url_launcher: ^6.1.5

  shared_preferences: ^2.0.15
  provider: ^6.0.3

  cached_network_image: ^3.2.2
  cached_video_player: ^2.0.3
  video_player: ^2.4.7
  flutter_rating_bar: ^4.0.1
  lottie: ^1.4.2 # NOT USED YET

  file_picker: ^4.6.1
  wechat_assets_picker: ^8.1.2
  image_cropper: ^3.0.0 # ANDROID INTEGRATION

  font_awesome_flutter: ^10.1.0
  intl: ^0.17.0

  linkfy_text: ^1.1.5
  flutter_social_textfield: ^0.1.0 # ONE OF THEM NEED TO REMOVE IN FUTURE
  flutter_mentions: ^2.0.1 # ONE OF THEM NEED TO REMOVE IN FUTURE

  fluttertoast: ^8.0.9

  dropdown_search: ^5.0.2
  currency_picker: ^2.0.11
  intl_phone_field: ^3.1.0

  carousel_slider: ^4.1.1
  scrollable_positioned_list: ^0.3.2

  fast_contacts: ^1.1.1

  story_viewer: ^0.2.0

  agora_rtm: ^1.1.1
  permission_handler: ^10.0.0
  agora_rtc_engine: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.11
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#C01719"
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  android: true
  ios: true
  # color_dark: "#000000"
  color: "#ffffff"
  image: assets/images/icon_border.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
